export const menulists = [
  {
    id: 1,
    path: "/",
    link: "home",
  },
];

export const categorylists = [
  {
    id: 1,
    image: "../images/category/cereals.png",
    title: "Cereals",
  },
  {
    id: 2,
    image: "../images/category/pulses.webp",
    title: "Pulses",
  },
  {
    id: 3,
    image: "../images/category/fruits.jpeg",
    title: "Fruits",
  },
  {
    id: 4,
    image: "../images/category/veggies.jpg",
    title: "Vegetables",
  },
  {
    id: 5,
    image: "../images/category/oilseeds.jpg",
    title: "Oilseeds",
  },
  {
    id: 6,
    image: "../images/category/spices.png",
    title: "Spices",
  },
  {
    id: 7,
    image: "../images/category/medicinal.png",
    title: "Medicinal"
  },
];

export const productlists = [
  {
    id: 1,
    image: "https://images.unsplash.com/photo-1437252611977-07f74518abd7?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8d2hlYXQlMjBoYXJ2ZXN0fGVufDB8fDB8fHww",
    title: "WHEAT TOP QUALITY",
    bprice: 853,
    price: 100,
    catgeory: "Cereals",
  },
  {
    id: 2,
    image: "https://media.istockphoto.com/id/519309790/photo/pile-of-raw-basmati-rice-with-a-spoon.jpg?s=612x612&w=0&k=20&c=A9A87HykypkOo5qLMQm6bZjBQn83NE1NHMppw8-6Tnc=",
    title: "BASMATI RICE",
    bprice: 452,
    price: 142,
    catgeory: "Cereals",
  },
  {
    id: 3,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRq6HIDADKT8lX3JYLBor04FFVVozpzU5Jmww&s",
    title: "KIDNEY BEANS",
    bprice: 105,
    price: 100,
    catgeory: "Pulses",
  },
  {
    id: 4,
    image: "https://thumbs.dreamstime.com/b/split-black-gram-crop-split-black-gram-crop-split-crop-pulses-crops-food-healthy-agriculture-grains-grams-158119098.jpg",
    title: "BLACK GRAM",
    bprice: 40000,
    price: 500,
    catgeory: "Pulses",
  },
  {
    id: 5,
    image: "https://iprod.mishry.com/wp-content/uploads/2020/05/19164755/mango-5224186_1280-1024x768.jpg",
    title: "ALPHONSO MANGO",
    bprice: 4000,
    price: 800,
    catgeory: "Fruits",
  },
  {
    id: 6,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPDi7461mN2OuKTNi_W7yeRIk0khxb2GsOyg&s",
    title: "SHIMLA APPLES",
    bprice: 40000,
    price: 500,
    catgeory: "Fruits",
  },
  {
    id: 6,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSungRAJWDJxxBLqxccucPcwq8YZ0P7P6k34Q&s",
    title: "CAULIFLOWER",
    bprice: 400,
    price: 80,
    catgeory: "Vegetables",
  },
  {
    id: 7,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2eq2ovn8jAuXdRaLst8Xi4Se8Ua85r3lkkg&s",
    title: "RED TOMATOES",
    bprice: 200,
    price: 50,
    catgeory: "Vegetables",
  },
  {
    id: 8,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRl8oyiqf_3BU0thgWzrjoKGsoxsW_EcMHvlg&s",
    title: "SUNFLOWER SEEDS",
    bprice: 200,
    price: 80,
    catgeory: "Oilseeds",
  },
  {
    id: 9,
    image: "https://media.istockphoto.com/id/1149840299/photo/wild-mustard-plant-in-flower.jpg?s=612x612&w=0&k=20&c=fv2AP-tpq8j8ohdfb9OAHFHOUbz_-6MtbJ43bHWB6mY=",
    title: "MUSTARD SEEDS",
    bprice: 853,
    price: 50,
    catgeory: "Oilseeds",
  },
  {
    id: 10,
    image: "https://images.unsplash.com/photo-1437252611977-07f74518abd7?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8d2hlYXQlMjBoYXJ2ZXN0fGVufDB8fDB8fHww",
    title: "WHEAT TOP QUALITY",
    bprice: 853,
    price: 100,
    catgeory: "Cereals",
  },
  {
    id: 11,
    image: "https://media.istockphoto.com/id/519309790/photo/pile-of-raw-basmati-rice-with-a-spoon.jpg?s=612x612&w=0&k=20&c=A9A87HykypkOo5qLMQm6bZjBQn83NE1NHMppw8-6Tnc=",
    title: "BASMATI RICE",
    bprice: 452,
    price: 142,
    catgeory: "Cereals",
  },
  {
    id: 1,
    image: "https://netstorm-react.theme-land.com/img/auction_4.jpg",
    title: "2018 Hyundai Sonata",
    bprice: 853,
    price: 5000,
  },
  {
    id: 1,
    image: "https://netstorm-react.theme-land.com/img/auction_5.jpg",
    title: "2018 Hyundai Sonata",
    bprice: 853,
    price: 5000,
  },
  {
    id: 1,
    image: "https://netstorm-react.theme-land.com/img/auction_6.jpg",
    title: "2018 Hyundai Sonata",
    bprice: 853,
    price: 5000,
  },
  {
    id: 1,
    image: "https://netstorm-react.theme-land.com/img/auction_7.jpg",
    title: "2018 Hyundai Sonata",
    bprice: 853,
    price: 5000,
  },
  {
    id: 1,
    image: "https://netstorm-react.theme-land.com/img/auction_8.jpg",
    title: "2018 Hyundai Sonata",
    bprice: 853,
    price: 5000,
  },
  {
    id: 1,
    image: "https://bidout-wp.b-cdn.net/wp-content/uploads/2022/10/Image-10.jpg",
    title: "2018 Hyundai Sonata",
    bprice: 853,
    price: 5000,
  },
  {
    id: 1,
    image: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/antiques-demo-product-09-768x768.jpg",
    title: "Watch Hyundai Sonata",
    bprice: 853,
    price: 5000,
  },
  {
    id: 1,
    image: "https://bidpro.webdevia.com/wp-content/uploads/2018/12/photo-1596568359553-a56de6970068-600x414.jpg",
    title: "Watch Hyundai Sonata",
    bprice: 853,
    price: 5000,
  },
  {
    id: 1,
    image: "https://bidpro.webdevia.com/wp-content/uploads/2018/05/florian-klauer-mk7D-4UCfmg-unsplash-600x414.jpg",
    title: "Watch Hyundai Sonata",
    bprice: 853,
    price: 5000,
  },
  {
    id: 1,
    image: "https://bidpro.webdevia.com/wp-content/uploads/2018/05/igor-karimov-59MGmlUiqwA-unsplash-600x414.jpg",
    title: "Watch Hyundai Sonata",
    bprice: 853,
    price: 5000,
  },
  {
    id: 1,
    image: "https://bidpro.webdevia.com/real-estate-auction-marketplace/wp-content/uploads/sites/5/2022/03/home-9-1-450x338.jpg",
    title: "Watch Hyundai Sonata",
    bprice: 853,
    price: 5000,
  },
  {
    id: 1,
    image: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/antiques-demo-product-10-768x768.jpg",
    title: "Watch Hyundai Sonata",
    bprice: 853,
    price: 5000,
  },
  {
    id: 1,
    image: "https://jew-theme.myshopify.com/cdn/shop/files/Rectangle_144.png?v=1703498789&width=1500",
    title: "Watch Hyundai Sonata",
    bprice: 853,
    price: 5000,
  },
  {
    id: 1,
    image: "https://themesflat.co/html/open9/assets/images/box-item/card-item-05.jpg",
    title: "2018 Hyundai Sonata",
    bprice: 853,
    price: 5000,
  },
  {
    id: 1,
    image: "https://themesflat.co/html/open9/assets/images/box-item/card-item-06.jpg",
    title: "Watch Hyundai Sonata",
    bprice: 853,
    price: 5000,
  },
  {
    id: 1,
    image: "https://themesflat.co/html/open9/assets/images/box-item/card-item-07.jpg",
    title: "Watch Hyundai Sonata",
    bprice: 853,
    price: 5000,
  },
  {
    id: 1,
    image: "https://themesflat.co/html/open9/assets/images/box-item/card-item-08.jpg",
    title: "Watch Hyundai Sonata",
    bprice: 853,
    price: 5000,
  },
  {
    id: 1,
    image: "https://themesflat.co/html/open9/assets/images/box-item/card-item-01.jpg",
    title: "Watch Hyundai Sonata",
    bprice: 853,
    price: 5000,
  },
  {
    id: 1,
    image: "https://themesflat.co/html/open9/assets/images/box-item/card-item-02.jpg",
    title: "Watch Hyundai Sonata",
    bprice: 853,
    price: 5000,
  },
  {
    id: 1,
    image: "https://themesflat.co/html/open9/assets/images/box-item/card-item-03.jpg",
    title: "Watch Hyundai Sonata",
    bprice: 853,
    price: 5000,
  },
  {
    id: 1,
    image: "https://themesflat.co/html/open9/assets/images/box-item/card-item-04.jpg",
    title: "Watch Hyundai Sonata",
    bprice: 853,
    price: 5000,
  },
];

export const processList = [
  {
    id: "01",
    title: "Sign up",
    desc: "Sign your crops up via our contact form. Send us a couple of pictures of the crops that you want to put up for auction.",
    cover: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/01/shape-7.png",
  },
  {
    id: "02",
    title: "Auction goes online",
    desc: "As soon as we collect enough crops for the auction, the auction will show up on the website.",
    cover: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/auction.png",
  },
  {
    id: "03",
    title: "Closing auction",
    desc: "After the viewing day(s) the auction is still a few days open for new bids. We evaluate the highest bid after the closing of an auction.",
    cover: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/auction-2.png",
  },
  {
    id: "04",
    title: "The last steps",
    desc: "After the crop is sold to the highest bidder, all the crops will be collected by the buyers on a determined date.",
    cover: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/auction-3.png",
  },
];

export const topSellerList = [
  {
    id: 1,
    title: "William",
    profile: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/01/client-5-1.png",
    amount: "100",
  },
  {
    id: 2,
    title: "Orko",
    profile: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/01/client-6.png",
    amount: "200",
  },
  {
    id: 3,
    title: "Nipa",
    profile: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/01/client-3.png",
    amount: "300",
  },
  {
    id: 4,
    title: "Joseph",
    profile: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/01/client-2-2.png",
    amount: "100",
  },
  {
    id: 5,
    title: "Isabella",
    profile: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/01/client-10-2.png",
    amount: "100",
  },
  {
    id: 6,
    title: "Emily",
    profile: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/01/client-15-1.png",
    amount: "100",
  },
  {
    id: 7,
    title: "Devmahbub",
    profile: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/01/client-8-3.png",
    amount: "100",
  },
  {
    id: 8,
    title: "Ava Garcia",
    profile: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/01/client-4-1.png",
    amount: "100",
  },
  {
    id: 9,
    title: "Amelia Harris",
    profile: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/01/client-13.png",
    amount: "100",
  },
  {
    id: 10,
    title: "Alexander",
    profile: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/01/client-8.png",
    amount: "100",
  },
];

export const trustList = [
  {
    id: 1,
    profile: "https://bidout-react.vercel.app/images/bg/sponsor1.png",
  },
  {
    id: 2,
    profile: "https://bidout-react.vercel.app/images/bg/sponsor3.png",
  },
  {
    id: 3,
    profile: "https://bidout-react.vercel.app/images/bg/sponsor2.png",
  },
  {
    id: 4,
    profile: "https://bidout-react.vercel.app/images/bg/sponsor4.png",
  },
  {
    id: 5,
    profile: "https://bidout-react.vercel.app/images/bg/sponsor5.png",
  },
  {
    id: 6,
    profile: "https://bidout-react.vercel.app/images/bg/sponsor6.png",
  },
  {
    id: 7,
    profile: "https://bidout-react.vercel.app/images/bg/sponsor7.png",
  },
  {
    id: 8,
    profile: "https://bidout-react.vercel.app/images/bg/sponsor8.png",
  },
  {
    id: 9,
    profile: "https://bidout-react.vercel.app/images/bg/sponsor9.png",
  },
  {
    id: 10,
    profile: "https://bidout-react.vercel.app/images/bg/sponsor1.png",
  },
  {
    id: 4,
    profile: "https://bidout-react.vercel.app/images/bg/sponsor3.png",
  },
  {
    id: 5,
    profile: "https://bidout-react.vercel.app/images/bg/sponsor8.png",
  },
  {
    id: 6,
    profile: "https://bidout-react.vercel.app/images/bg/sponsor1.png",
  },
  {
    id: 7,
    profile: "https://bidout-react.vercel.app/images/bg/sponsor9.png",
  },
];

export const topList = [
  {
    id: 1,
    catgeory: "Luxury Vehicles",
    total: 7,
    img1: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/automotive_product-01-300x200.jpg",
    img2: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/automotive_product-07-150x150.jpg",
    img3: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/automotive_product-03-150x150.jpg",
    img4: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/automotive_product-08-150x150.jpg",
  },
  {
    id: 2,
    catgeory: "Classic",
    total: 10,
    img1: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/automotive_product-09-300x200.jpg",
    img2: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/automotive_product-01-150x150.jpg",
    img3: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/automotive_product-07-150x150.jpg",
    img4: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/automotive_product-03-150x150.jpg",
  },
  {
    id: 3,
    catgeory: "Muscle Machines",
    total: 8,
    img1: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/automotive_product-07-300x200.jpg",
    img2: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/automotive_product-03-150x150.jpg",
    img4: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/automotive_product-07-150x150.jpg",
    img3: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/automotive_product-01-150x150.jpg",
  },
  {
    id: 4,
    catgeory: "Automotive",
    total: 4,
    img3: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/automotive_product-05-300x200.jpg",
    img2: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/automotive_product-05-768x768.jpg",
    img4: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/automotive_product-07-150x150.jpg",
    img1: "https://rainbowthemes.net/themes/nuron/wp-content/uploads/2023/09/automotive_product-04-768x768.jpg",
  },
];
